[project]
name = "alien-invasion"
version = "0.1.0"
description = "Учебный проект по книге Изучаем Python Мэтиз Э..pdf"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]
